apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    k8s.course.label: deployments
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        version: v1
    spec:
      containers:
        - name: app
          image: thecodecamp/whoami:latest