services:
  random-api:
    image: thecodecamp/random-api:latest
    secrets:
      - source: dotnet-logging
        target: /app/config/logging.json
      - source: random-api
        target: /app/config/override.json
    networks:
      - app-net

  random-ui:
    image: thecodecamp/random-ui:latest
    secrets:
      - source: dotnet-logging
        target: /app/config/logging.json
      - source: random-ui
        target: /app/config/override.json
    networks:
      - app-net

networks:
  app-net:
