services:
  random-api:
    ports:
      - "8189:80"

  random-ui:
    ports:
      - "8190:80"

secrets:
  dotnet-logging:
    file: ./config/dev/logging.json
  random-api:
    file: ./config/dev/api/override.json
  random-ui:
    file: ./config/dev/web/override.json
