services:
  random-api:
    image: thecodecamp/random-api:latest
    env_file: ./config/logging.env
    ports:
      - "8089:80"
    networks:
      - app-net

  random-ui:
    image: thecodecamp/random-ui:latest
    env_file: ./config/logging.env
    environment:
      - RngApi__Url=http://random-api/rng
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net: