services:
  random-api:
    image: thecodecamp/random-api:latest
    volumes:
      - ./config/dev/logging.json:/app/config/logging.json
    secrets:
      - source: random-api
        target: /app/config/override.json
    ports:
      - "8089:80"
    networks:
      - app-net

  random-ui:
    image: thecodecamp/random-ui:latest
    volumes:
      - ./config/dev/logging.json:/app/config/logging.json
    secrets:
      - source: random-ui
        target: /app/config/override.json
    environment:
      - RngApi__Url=http://random-api/rng
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net:

secrets:
  random-api:
    file: ./config/dev/api/override.json
  random-ui:
    file: ./config/dev/web/override.json
