apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    k8s.course.label: services
spec:
  selector:
    app: whoami
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP