services:
  api-server:
    image: thecodecamp/banking-api:latest
    environment:
      - AUTH_ENABLED=0
    restart: always
    volumes: 
      - ./scripts:/scripts
    networks:
      app-net: 
        ipv4_address: 10.218.0.10

  web:
    image: thecodecamp/banking-ui:latest
    ports:
      - "8090:80"
    networks:
      - app-net

  customers-db:
    image: thecodecamp/customers-db:latest
    networks:
      - app-net

networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: 10.218.0.0/16
