services:
  api-server:
    image: thecodecamp/banking-api:latest
    environment:
      - AUTH_ENABLED=0
    restart: always
    networks:
      - app-net

  web:
    image: thecodecamp/banking-ui:latest
    ports:
      - "8090:80"
    networks:
      - app-net

  customers-db:
    image: thecodecamp/customers-db:latest
    networks:
      - app-net

networks:
  app-net:
